name: Promote to PRODUCTION

on:
  workflow_dispatch:
  push:
    branches: [ "staging" ]
  

jobs:

  gather:
    name: Gather Promotion Facts
    runs-on: ubuntu-20.04
    outputs:
      shortsha: ${{ steps.facts.outputs.shortsha }}
    steps:
      - id: facts
        run: echo "shortsha=$(echo $GITHUB_SHA | cut -c1-7)" >> "$GITHUB_OUTPUT"

  verify:
    name: Review Promote ${{needs.gather.outputs.shortsha}} to Staging
    needs: gather
    env:
      shortsha: ${{needs.gather.outputs.shortsha}}
    environment: staging
    runs-on: ubuntu-20.04
    steps:
      - run: echo $shortsha

  perform:
    name: Promote ${{needs.gather.outputs.shortsha}} to Staging
    needs:
      - gather
      - verify
    env:
      shortsha: ${{needs.gather.outputs.shortsha}}
    runs-on: ubuntu-20.04
    steps:
      - uses: imranismail/setup-kustomize@v2
      - uses: actions/checkout@v4.1.0
        with:
          ref: staging
      - run: |
          cd base/
          kustomize edit set image app:$shortsha
          cd ..
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git add .
          git commit -m "Updated STAGING Image Tag to ${shortsha}"
          git push
