name: Deploy via GitOps Promotion

on:
  workflow_call:
    inputs:
      sourceEnvironment:
        description: 'Source Environment'
        required: true
        type: string
      targetEnvironment:
        description: 'Target Environment'
        required: true
        type: string
  
jobs:
  gather:
    name: Gather Promotion Facts
    runs-on: ubuntu-20.04
    outputs:
      imageSha: ${{ steps.facts.outputs.imageSha }}
    env:
      sourceEnv: ${{ inputs.sourceEnvironment }}
    steps:
      - id: facts
        run: echo "imageSha=$(cat overlays/$sourceEnv/kustomization.yaml | grep newTag | sed 's/^.*: //g')" >> "$GITHUB_OUTPUT"

  perform:
    name: Promote ${{ needs.gather.outputs.imageSha }} to ${{ inputs.targetEnvironment }}
    needs:
      - gather
    env:
      imageSha: ${{needs.gather.outputs.imageSha}}
      targetEnv: ${{ inputs.targetEnvironment }}
    environment: ${{ inputs.targetEnvironment }}
    runs-on: ubuntu-20.04
    steps:
      - uses: imranismail/setup-kustomize@v2
      - run: |
          cd overlays/$targetEnv
          kustomize edit set image app:$imageSha
          cd ..
          git config user.email "automated@redhat.com"
          git config user.name "Automated Pipeline"
          git add .
          git commit -m "Updated ${targetEnv} Image Tag to ${imageSha}"
          git push
